package proxy

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const (
	testBaseDomain    = "example.com"
	testDashboardHost = "deploy.example.com"
	testACMEEmail     = "ops@example.com"
)

// testConfig returns a config pointing at a path inside dir.
func testConfig(dir string) Config {
	return Config{
		BaseDomain:    testBaseDomain,
		DashboardHost: testDashboardHost,
		ACMEEmail:     testACMEEmail,
		CaddyfilePath: filepath.Join(dir, "Caddyfile"),
		ReloadBinary:  "caddy",
		ReloadArgs:    []string{"reload", "--config", filepath.Join(dir, "Caddyfile")},
	}
}

type reloadCall struct {
	binary string
	args   []string
}

// stubReload returns a reload implementation that records every invocation and
// then fails with failWith, so a test can assert both the arguments used and
// the error reaching Apply.
func stubReload(failWith error, calls *[]reloadCall) func(context.Context, string, []string) error {
	return func(_ context.Context, binary string, args []string) error {
		*calls = append(*calls, reloadCall{binary: binary, args: args})
		return failWith
	}
}

func TestRouteValidate(t *testing.T) {
	cases := []struct {
		name    string
		route   Route
		wantErr string
	}{
		{
			name:  "valid project route",
			route: Route{Host: "my-app.example.com", Upstream: "127.0.0.1:32768"},
		},
		{
			name:  "valid dashboard route",
			route: Route{Host: testDashboardHost, Upstream: "127.0.0.1:8080", Dashboard: true},
		},
		{
			name:    "empty host",
			route:   Route{Upstream: "127.0.0.1:32768"},
			wantErr: "host is required",
		},
		{
			name:    "whitespace host",
			route:   Route{Host: "   ", Upstream: "127.0.0.1:32768"},
			wantErr: "host is required",
		},
		{
			name:    "empty upstream",
			route:   Route{Host: "my-app.example.com"},
			wantErr: "upstream is required",
		},
		{
			name:    "whitespace upstream",
			route:   Route{Host: "my-app.example.com", Upstream: "  "},
			wantErr: "upstream is required",
		},
		{
			name:    "host with a space",
			route:   Route{Host: "foo bar", Upstream: "127.0.0.1:32768"},
			wantErr: `host "foo bar" is not a valid hostname`,
		},
		{
			name:    "host with an empty label",
			route:   Route{Host: "foo..bar", Upstream: "127.0.0.1:32768"},
			wantErr: `host "foo..bar" is not a valid hostname`,
		},
		{
			name:    "host with a leading dot",
			route:   Route{Host: ".foo", Upstream: "127.0.0.1:32768"},
			wantErr: `host ".foo" is not a valid hostname`,
		},
		{
			name:    "host with a trailing dot",
			route:   Route{Host: "foo.", Upstream: "127.0.0.1:32768"},
			wantErr: `host "foo." is not a valid hostname`,
		},
		{
			name:    "host with an underscore",
			route:   Route{Host: "my_app.example.com", Upstream: "127.0.0.1:32768"},
			wantErr: `host "my_app.example.com" is not a valid hostname`,
		},
		{
			name:    "upstream without a port",
			route:   Route{Host: "my-app.example.com", Upstream: "notaport"},
			wantErr: `upstream "notaport" must be host:port`,
		},
		{
			name:    "upstream with a non numeric port",
			route:   Route{Host: "my-app.example.com", Upstream: "host:abc"},
			wantErr: `upstream "host:abc" must be host:port`,
		},
		{
			name:    "upstream with two ports",
			route:   Route{Host: "my-app.example.com", Upstream: "host:80:90"},
			wantErr: `upstream "host:80:90" must be host:port`,
		},
		{
			name:    "upstream with an empty port",
			route:   Route{Host: "my-app.example.com", Upstream: "host:"},
			wantErr: `upstream "host:" must be host:port`,
		},
		{
			name:    "upstream with an empty host",
			route:   Route{Host: "my-app.example.com", Upstream: ":8080"},
			wantErr: `upstream ":8080" must be host:port`,
		},
		{
			name:    "upstream port out of range",
			route:   Route{Host: "my-app.example.com", Upstream: "127.0.0.1:70000"},
			wantErr: `upstream "127.0.0.1:70000" must be host:port`,
		},
		{
			name:    "host reported before upstream",
			route:   Route{Host: "foo bar"},
			wantErr: `host "foo bar" is not a valid hostname`,
		},
	}

	for _, testCase := range cases {
		t.Run(testCase.name, func(t *testing.T) {
			err := testCase.route.Validate()
			if testCase.wantErr == "" {
				if err != nil {
					t.Fatalf("Route.Validate() error = %v, want nil", err)
				}
				return
			}
			if err == nil {
				t.Fatalf("Route.Validate() error = nil, want %q", testCase.wantErr)
			}
			if err.Error() != testCase.wantErr {
				t.Fatalf("Route.Validate() error = %q, want %q", err.Error(), testCase.wantErr)
			}
		})
	}
}

func TestRenderWithNoRoutes(t *testing.T) {
	got := Render(testConfig(t.TempDir()), nil)

	want := "# Generated by deploy-platform. Edits are overwritten on the next deploy.\n" +
		"# Base domain: example.com\n" +
		"{\n" +
		"\temail ops@example.com\n" +
		"}\n"
	if got != want {
		t.Fatalf("Render() = %q, want %q", got, want)
	}
	if strings.Contains(got, "reverse_proxy") {
		t.Errorf("Render() = %q, want no site block", got)
	}
}

func TestRenderRoutes(t *testing.T) {
	config := testConfig(t.TempDir())
	routes := []Route{
		{Host: "pay-api.example.com", Upstream: "127.0.0.1:32770"},
		{Host: testDashboardHost, Upstream: "127.0.0.1:8080", Dashboard: true},
		{Host: "my-app.example.com", Upstream: "127.0.0.1:32768"},
	}

	got := Render(config, routes)

	for _, want := range []string{
		"\temail ops@example.com\n",
		"deploy.example.com {\n\treverse_proxy 127.0.0.1:8080 {\n\t\theader_up Host {host}\n\t\theader_up X-Forwarded-Proto https\n\t}\n}\n",
		"my-app.example.com {\n\treverse_proxy 127.0.0.1:32768\n}\n",
		"pay-api.example.com {\n\treverse_proxy 127.0.0.1:32770\n}\n",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("Render() = %q, want it to contain %q", got, want)
		}
	}

	// Dashboard first, then projects sorted by host.
	wantOrder := []string{"deploy.example.com", "my-app.example.com", "pay-api.example.com"}
	position := 0
	for _, host := range wantOrder {
		index := strings.Index(got, host+" {\n")
		if index < 0 {
			t.Fatalf("Render() = %q, want a site block for %q", got, host)
		}
		if index < position {
			t.Errorf("Render() = %q, want %q after the previous site", got, host)
		}
		position = index
	}
}

func TestRenderKeepsDashboardFirstRegardlessOfHostOrder(t *testing.T) {
	config := testConfig(t.TempDir())
	routes := []Route{
		{Host: "aaa-first-alphabetically.example.com", Upstream: "127.0.0.1:32768"},
		{Host: testDashboardHost, Upstream: "127.0.0.1:8080", Dashboard: true},
	}

	got := Render(config, routes)

	dashboard := strings.Index(got, testDashboardHost+" {\n")
	project := strings.Index(got, "aaa-first-alphabetically.example.com {\n")
	if dashboard < 0 || project < 0 {
		t.Fatalf("Render() = %q, want both site blocks", got)
	}
	if dashboard > project {
		t.Errorf("Render() = %q, want the dashboard site before the project site", got)
	}
}

func TestRenderWithoutACMEEmail(t *testing.T) {
	config := testConfig(t.TempDir())
	config.ACMEEmail = ""

	got := Render(config, []Route{{Host: "my-app.example.com", Upstream: "127.0.0.1:32768"}})

	if strings.Contains(got, "email") {
		t.Errorf("Render() = %q, want no email directive", got)
	}
	if !strings.Contains(got, "{\n}\n") {
		t.Errorf("Render() = %q, want an empty global options block", got)
	}
}

func TestRenderIsDeterministic(t *testing.T) {
	config := testConfig(t.TempDir())
	routes := []Route{
		{Host: "pay-api.example.com", Upstream: "127.0.0.1:32770"},
		{Host: testDashboardHost, Upstream: "127.0.0.1:8080", Dashboard: true},
		{Host: "my-app.example.com", Upstream: "127.0.0.1:32768"},
	}

	first := Render(config, routes)
	for i := 0; i < 5; i++ {
		if got := Render(config, routes); got != first {
			t.Fatalf("Render() call %d = %q, want %q", i+2, got, first)
		}
	}

	// The same routes in a different order must render the same bytes, which is
	// the property that keeps an unchanged deploy from reloading the proxy.
	shuffled := []Route{routes[2], routes[0], routes[1]}
	if got := Render(config, shuffled); got != first {
		t.Errorf("Render(shuffled) = %q, want %q", got, first)
	}

	// Render must not sort the caller's slice in place.
	if routes[0].Host != "pay-api.example.com" {
		t.Errorf("Render() reordered the caller's routes: routes[0].Host = %q", routes[0].Host)
	}
}

func TestRenderEndsWithNewline(t *testing.T) {
	config := testConfig(t.TempDir())

	for _, routes := range [][]Route{
		nil,
		{{Host: "my-app.example.com", Upstream: "127.0.0.1:32768"}},
		{{Host: testDashboardHost, Upstream: "127.0.0.1:8080", Dashboard: true}},
	} {
		got := Render(config, routes)
		if !strings.HasSuffix(got, "\n") {
			t.Errorf("Render(%v) = %q, want a trailing newline", routes, got)
		}
	}
}

func TestNewCaddyWriter(t *testing.T) {
	cases := []struct {
		name    string
		config  Config
		wantErr string
	}{
		{
			name:   "valid config",
			config: testConfig(t.TempDir()),
		},
		{
			name: "missing caddyfile path",
			config: Config{
				BaseDomain: testBaseDomain,
			},
			wantErr: "caddyfile path is required",
		},
		{
			name: "whitespace caddyfile path",
			config: Config{
				BaseDomain:    testBaseDomain,
				CaddyfilePath: "  ",
			},
			wantErr: "caddyfile path is required",
		},
		{
			name: "missing base domain",
			config: Config{
				CaddyfilePath: filepath.Join(t.TempDir(), "Caddyfile"),
			},
			wantErr: "base domain is required",
		},
	}

	for _, testCase := range cases {
		t.Run(testCase.name, func(t *testing.T) {
			writer, err := NewCaddyWriter(testCase.config)
			if testCase.wantErr != "" {
				if err == nil {
					t.Fatalf("NewCaddyWriter() error = nil, want %q", testCase.wantErr)
				}
				if err.Error() != testCase.wantErr {
					t.Fatalf("NewCaddyWriter() error = %q, want %q", err.Error(), testCase.wantErr)
				}
				if writer != nil {
					t.Fatalf("NewCaddyWriter() writer = %v, want nil", writer)
				}
				return
			}
			if err != nil {
				t.Fatalf("NewCaddyWriter() error = %v, want nil", err)
			}
			if writer.reload == nil {
				t.Error("NewCaddyWriter() reload = nil, want the exec implementation")
			}
		})
	}
}

func TestApplyWritesFile(t *testing.T) {
	dir := t.TempDir()
	config := testConfig(dir)
	var calls []reloadCall

	writer, err := NewCaddyWriter(config)
	if err != nil {
		t.Fatalf("NewCaddyWriter() error = %v", err)
	}
	writer.reload = stubReload(nil, &calls)

	routes := []Route{
		{Host: testDashboardHost, Upstream: "127.0.0.1:8080", Dashboard: true},
		{Host: "my-app.example.com", Upstream: "127.0.0.1:32768"},
	}
	if err := writer.Apply(routes); err != nil {
		t.Fatalf("Apply() error = %v, want nil", err)
	}

	written, err := os.ReadFile(config.CaddyfilePath)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	if want := Render(config, routes); string(written) != want {
		t.Errorf("file content = %q, want %q", string(written), want)
	}

	if len(calls) != 1 {
		t.Fatalf("reload calls = %d, want 1", len(calls))
	}
	if calls[0].binary != config.ReloadBinary {
		t.Errorf("reload binary = %q, want %q", calls[0].binary, config.ReloadBinary)
	}
	if strings.Join(calls[0].args, " ") != strings.Join(config.ReloadArgs, " ") {
		t.Errorf("reload args = %q, want %q", calls[0].args, config.ReloadArgs)
	}
}

func TestApplyReplacesExistingFile(t *testing.T) {
	dir := t.TempDir()
	config := testConfig(dir)
	// A hand edited file with content the platform does not generate.
	stale := "# hand edited\ndeploy.example.com {\n\treverse_proxy 127.0.0.1:1\n}\n"
	if err := os.WriteFile(config.CaddyfilePath, []byte(stale), 0o644); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}

	writer, err := NewCaddyWriter(config)
	if err != nil {
		t.Fatalf("NewCaddyWriter() error = %v", err)
	}
	var calls []reloadCall
	writer.reload = stubReload(nil, &calls)

	routes := []Route{{Host: "my-app.example.com", Upstream: "127.0.0.1:32768"}}
	if err := writer.Apply(routes); err != nil {
		t.Fatalf("Apply() error = %v, want nil", err)
	}

	written, err := os.ReadFile(config.CaddyfilePath)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	if want := Render(config, routes); string(written) != want {
		t.Errorf("file content = %q, want %q", string(written), want)
	}
	if strings.Contains(string(written), "hand edited") {
		t.Errorf("file content = %q, want the hand edited content dropped", string(written))
	}
}

func TestApplyRejectsInvalidRoutesWithoutWriting(t *testing.T) {
	cases := []struct {
		name    string
		routes  []Route
		wantErr string
	}{
		{
			name:    "invalid route",
			routes:  []Route{{Host: "my-app.example.com", Upstream: "127.0.0.1:32768"}, {Host: "foo..bar", Upstream: "127.0.0.1:32769"}},
			wantErr: `route 1: host "foo..bar" is not a valid hostname`,
		},
		{
			name:    "empty host",
			routes:  []Route{{Host: "", Upstream: "127.0.0.1:32768"}},
			wantErr: "route 0: host is required",
		},
		{
			name:    "invalid upstream",
			routes:  []Route{{Host: "my-app.example.com", Upstream: "127.0.0.1"}},
			wantErr: `route 0: upstream "127.0.0.1" must be host:port`,
		},
		{
			name: "duplicate host",
			routes: []Route{
				{Host: "my-app.example.com", Upstream: "127.0.0.1:32768"},
				{Host: "my-app.example.com", Upstream: "127.0.0.1:32769"},
			},
			wantErr: `duplicate route host "my-app.example.com"`,
		},
		{
			name: "duplicate host with different case",
			routes: []Route{
				{Host: "my-app.example.com", Upstream: "127.0.0.1:32768"},
				{Host: "My-App.example.com", Upstream: "127.0.0.1:32769"},
			},
			wantErr: `duplicate route host "My-App.example.com"`,
		},
	}

	for _, testCase := range cases {
		t.Run(testCase.name, func(t *testing.T) {
			dir := t.TempDir()
			config := testConfig(dir)
			var calls []reloadCall

			writer, err := NewCaddyWriter(config)
			if err != nil {
				t.Fatalf("NewCaddyWriter() error = %v", err)
			}
			writer.reload = stubReload(nil, &calls)

			if err := writer.Apply(testCase.routes); err == nil {
				t.Fatalf("Apply() error = nil, want %q", testCase.wantErr)
			} else if err.Error() != testCase.wantErr {
				t.Fatalf("Apply() error = %q, want %q", err.Error(), testCase.wantErr)
			}

			if _, err := os.Stat(config.CaddyfilePath); !os.IsNotExist(err) {
				t.Errorf("os.Stat(%q) error = %v, want not exist", config.CaddyfilePath, err)
			}
			if len(calls) != 0 {
				t.Errorf("reload calls = %d, want 0", len(calls))
			}
			entries, err := os.ReadDir(dir)
			if err != nil {
				t.Fatalf("ReadDir() error = %v", err)
			}
			if len(entries) != 0 {
				t.Errorf("dir contains %d entries, want 0", len(entries))
			}
		})
	}
}

func TestApplyRejectsDuplicateHostWithoutModifyingExistingFile(t *testing.T) {
	dir := t.TempDir()
	config := testConfig(dir)
	existing := "# installed earlier\n"
	if err := os.WriteFile(config.CaddyfilePath, []byte(existing), 0o644); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}

	writer, err := NewCaddyWriter(config)
	if err != nil {
		t.Fatalf("NewCaddyWriter() error = %v", err)
	}
	var calls []reloadCall
	writer.reload = stubReload(nil, &calls)

	routes := []Route{
		{Host: "my-app.example.com", Upstream: "127.0.0.1:32768"},
		{Host: "my-app.example.com", Upstream: "127.0.0.1:32769"},
	}
	if err := writer.Apply(routes); err == nil {
		t.Fatal("Apply() error = nil, want a duplicate host error")
	}

	written, err := os.ReadFile(config.CaddyfilePath)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	if string(written) != existing {
		t.Errorf("file content = %q, want it untouched (%q)", string(written), existing)
	}
	if len(calls) != 0 {
		t.Errorf("reload calls = %d, want 0", len(calls))
	}
}

func TestApplyReturnsReloadError(t *testing.T) {
	dir := t.TempDir()
	config := testConfig(dir)
	reloadErr := errors.New("exit status 1: adapting config: caddyfile:3: unknown directive")

	writer, err := NewCaddyWriter(config)
	if err != nil {
		t.Fatalf("NewCaddyWriter() error = %v", err)
	}
	var calls []reloadCall
	writer.reload = stubReload(reloadErr, &calls)

	routes := []Route{{Host: "my-app.example.com", Upstream: "127.0.0.1:32768"}}
	if err := writer.Apply(routes); !errors.Is(err, reloadErr) {
		t.Fatalf("Apply() error = %v, want %v", err, reloadErr)
	}

	// The file is installed even when the reload fails: Caddy may pick the
	// change up from disk, and losing the new routes would be worse.
	if _, err := os.Stat(config.CaddyfilePath); err != nil {
		t.Errorf("os.Stat(%q) error = %v, want the file installed", config.CaddyfilePath, err)
	}
}

func TestApplyWithoutReloadBinaryDoesNotRunReload(t *testing.T) {
	dir := t.TempDir()
	config := testConfig(dir)
	config.ReloadBinary = ""
	config.ReloadArgs = nil

	writer, err := NewCaddyWriter(config)
	if err != nil {
		t.Fatalf("NewCaddyWriter() error = %v", err)
	}
	var calls []reloadCall
	writer.reload = stubReload(errors.New("must not run"), &calls)

	routes := []Route{{Host: "my-app.example.com", Upstream: "127.0.0.1:32768"}}
	if err := writer.Apply(routes); err != nil {
		t.Fatalf("Apply() error = %v, want nil", err)
	}
	if len(calls) != 0 {
		t.Fatalf("reload calls = %d, want 0", len(calls))
	}
	if _, err := os.Stat(config.CaddyfilePath); err != nil {
		t.Errorf("os.Stat(%q) error = %v, want the file installed", config.CaddyfilePath, err)
	}
}

func TestApplyWithEmptyRouteSet(t *testing.T) {
	dir := t.TempDir()
	config := testConfig(dir)

	writer, err := NewCaddyWriter(config)
	if err != nil {
		t.Fatalf("NewCaddyWriter() error = %v", err)
	}
	var calls []reloadCall
	writer.reload = stubReload(nil, &calls)

	if err := writer.Apply(nil); err != nil {
		t.Fatalf("Apply() error = %v, want nil", err)
	}
	written, err := os.ReadFile(config.CaddyfilePath)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	if want := Render(config, nil); string(written) != want {
		t.Errorf("file content = %q, want %q", string(written), want)
	}
	if len(calls) != 1 {
		t.Errorf("reload calls = %d, want 1", len(calls))
	}
}

func TestApplyIsIdempotent(t *testing.T) {
	dir := t.TempDir()
	config := testConfig(dir)

	writer, err := NewCaddyWriter(config)
	if err != nil {
		t.Fatalf("NewCaddyWriter() error = %v", err)
	}
	var calls []reloadCall
	writer.reload = stubReload(nil, &calls)

	routes := []Route{
		{Host: "my-app.example.com", Upstream: "127.0.0.1:32768"},
		{Host: testDashboardHost, Upstream: "127.0.0.1:8080", Dashboard: true},
	}
	if err := writer.Apply(routes); err != nil {
		t.Fatalf("Apply() error = %v", err)
	}
	first, err := os.ReadFile(config.CaddyfilePath)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	// Same routes, reverse order.
	if err := writer.Apply([]Route{routes[1], routes[0]}); err != nil {
		t.Fatalf("Apply() error = %v", err)
	}
	second, err := os.ReadFile(config.CaddyfilePath)
	if err != nil {
		t.Fatalf("ReadFile() error = %v", err)
	}
	if string(first) != string(second) {
		t.Errorf("second Apply() = %q, want %q", string(second), string(first))
	}
	if len(calls) != 2 {
		t.Errorf("reload calls = %d, want 2", len(calls))
	}

	// No temp file may survive a successful apply.
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("ReadDir() error = %v", err)
	}
	if len(entries) != 1 || entries[0].Name() != filepath.Base(config.CaddyfilePath) {
		t.Errorf("dir entries = %v, want only %q", entries, filepath.Base(config.CaddyfilePath))
	}
}

func TestApplyOnMissingDirectoryFails(t *testing.T) {
	config := testConfig(t.TempDir())
	config.CaddyfilePath = filepath.Join(config.CaddyfilePath, "nested", "Caddyfile")

	writer, err := NewCaddyWriter(config)
	if err != nil {
		t.Fatalf("NewCaddyWriter() error = %v", err)
	}
	var calls []reloadCall
	writer.reload = stubReload(nil, &calls)

	if err := writer.Apply([]Route{{Host: "my-app.example.com", Upstream: "127.0.0.1:32768"}}); err == nil {
		t.Fatal("Apply() error = nil, want a write error")
	}
	if len(calls) != 0 {
		t.Errorf("reload calls = %d, want 0", len(calls))
	}
}

func TestNoopWriter(t *testing.T) {
	var writer Writer = NoopWriter{}

	if err := writer.Apply([]Route{{Host: "foo bar", Upstream: "notaport"}}); err != nil {
		t.Fatalf("NoopWriter.Apply() error = %v, want nil", err)
	}
	if err := writer.Apply(nil); err != nil {
		t.Fatalf("NoopWriter.Apply() error = %v, want nil", err)
	}
}

func TestExecReloadReportsFailure(t *testing.T) {
	// A binary that certainly does not exist exercises the real os/exec path.
	if err := execReload(context.Background(), "definitely-not-a-real-binary-xyz", nil); err == nil {
		t.Fatal("execReload() error = nil, want a failure")
	} else if !strings.Contains(err.Error(), "reload command failed") {
		t.Errorf("execReload() error = %q, want it to mention the reload command", err.Error())
	}
}
